In [80]:
!pip install -U fortran-magic
%reload_ext fortranmagic

!pip install --upgrade pandas-datareader

import pandas_datareader as pdr
import datetime

import pandas as pd
import numpy as np
from statsmodels.tsa.stattools import adfuller
import matplotlib.pylab as plt
from matplotlib.pylab import rcParams

!pip install --upgrade quandl
!pip install yfinance
import yfinance as yf




%matplotlib inline
%load_ext fortranmagic

import sys; sys.path.append('..')

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))

ran_the_first_cell = True

jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00', 
                             '2017-01-07 00:00:00+00:00', 
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])

/usr/local/lib/python3.7/dist-packages/fortranmagic.py:147: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module since IPython 4.0.
  self._lib_dir = os.path.join(get_ipython_cache_dir(), 'fortran')


The fortranmagic extension is already loaded. To reload it, use:
  %reload_ext fortranmagic


<center>
  <h1>The PyData Toolbox</h1>
  <h3>Scott Sanderson (Twitter: @scottbsanderson, GitHub: ssanderson)</h3>
  <h3><a href="https://github.com/ssanderson/pydata-toolbox">https://github.com/ssanderson/pydata-toolbox</a></h3>
</center>

## Outline

- Built-in Data Structures
- Numpy `array`
- Pandas `Series`/`DataFrame`
- Plotting and "Real-World" Analyses

# Data Structures

> Rule 5. Data dominates. If you've chosen the right data structures and organized things well, the algorithms
will almost always be self-evident. Data structures, not algorithms, are central to programming.

- *Notes on Programming in C*, by Rob Pike.

# Lists

In [115]:
assert ran_the_first_cell, "Oh noes!"

In [116]:
l = [1, 'two', 3.0, 4, 5.0, "six"]
l

[1, 'two', 3.0, 4, 5.0, 'six']

# Ejemplo 1:

In [83]:

h = [999, 'perro', 9, 9.28252, 2551, "nueve"]
h

[999, 'perro', 9, 9.28252, 2551, 'nueve']

In [117]:
# Lists can be indexed like C-style arrays.
first = l[0]
second = l[1]
print("first:", first)
print("second:", second)

first: 1
second: two


#Ejemplo 2:

In [119]:

primero = h[0]
segundo = h[1]
print("primero:", primero)
print("segundo:", segundo)


primero: 999
segundo: perro


In [120]:
# Negative indexing gives elements relative to the end of the list.
last = l[-1]
penultimate = l[-2]
print("last:", last)
print("second to last:", penultimate)

last: six
second to last: 5.0


#Ejemplo 3

In [121]:

ultimo = h[-1]
penultimo = h[-2]
print("ultimo:", ultimo)
print("penultimo:", penultimo)

ultimo: nueve
penultimo: 2551


In [122]:
# Lists can also be sliced, which makes a copy of elements between 
# start (inclusive) and stop (exclusive)
sublist = l[1:3]
sublist

['two', 3.0]

#Ejemplo 4

In [123]:
sublista = x[0:2]
sublista


[[9, 8, 7], [83, 150, 12]]

In [124]:
# l[:N] is equivalent to l[0:N].
first_three = l[:3]
first_three

[1, 'two', 3.0]

#Ejemplo 5

In [125]:

primero_tercero = h[:3]
primero_tercero


[999, 'perro', 9]

In [127]:
# l[3:] is equivalent to l[3:len(l)].
after_three = l[3:]
after_three

[4, 5.0, 'six']

#Ejemplo 6

In [128]:

despues_tres = x[3:]
despues_tres

[[201, 242, 244]]

In [129]:
# There's also a third parameter, "step", which gets every Nth element.
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h']
l[1:7:2]

['b', 'd', 'f']

#Ejemplo 7

In [130]:

e = ['h', 'e', 'r', 'n', 'a', 'n', 'f','e']
e[1:8:2]


['e', 'n', 'n', 'e']

In [131]:
# This is a cute way to reverse a list.
l[::-1]

['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

#Ejemplo 8

In [132]:

e[::-1]


['e', 'f', 'n', 'a', 'n', 'r', 'e', 'h']

In [133]:
# Lists can be grown efficiently (in O(1) amortized time).
l = [1, 2, 3, 4, 5]
print("Before:", l)
l.append('six')
print("After:", l)

Before: [1, 2, 3, 4, 5]
After: [1, 2, 3, 4, 5, 'six']


#Ejemplo 9

In [134]:

x = [9, 8, 7, 6, 5]
print("Antes:", x)
x.append('perro')
print("despues:", x)

Antes: [9, 8, 7, 6, 5]
despues: [9, 8, 7, 6, 5, 'perro']


In [135]:
# Comprehensions let us perform elementwise computations.
l = [1, 2, 3, 4, 5]
[x * 2 for x in l]

[2, 4, 6, 8, 10]

#Ejemplo 10:

In [136]:
x = [9, 8, 7, 6, 10]
[y * 2 for y in x]

[18, 16, 14, 12, 20]

## Review: Python Lists

- Zero-indexed sequence of arbitrary Python values.
- Slicing syntax: `l[start:stop:step]` copies elements at regular intervals from `start` to `stop`.
- Efficient (`O(1)`) appends and removes from end.
- Comprehension syntax: `[f(x) for x in l if cond(x)]`.

# Dictionaries

In [137]:
# Dictionaries are key-value mappings.
philosophers = {'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}
philosophers

{'Bertrand': 'Russell', 'David': 'Hume', 'Immanuel': 'Kant'}

#Ejemplo 11:

In [138]:
estudiantes = {'hernan': 'felipe', 'perdomo': 'morales', 'daniel': 'angelo'}
estudiantes

{'daniel': 'angelo', 'hernan': 'felipe', 'perdomo': 'morales'}

In [139]:
# Like lists, dictionaries are size-mutable.
philosophers['Ludwig'] = 'Wittgenstein'
philosophers

{'Bertrand': 'Russell',
 'David': 'Hume',
 'Immanuel': 'Kant',
 'Ludwig': 'Wittgenstein'}

#Ejemplo 12:

In [140]:

estudiantes['hernan'] = 'el mejor'
estudiantes


{'daniel': 'angelo', 'hernan': 'el mejor', 'perdomo': 'morales'}

In [141]:
del philosophers['David']
philosophers

{'Bertrand': 'Russell', 'Immanuel': 'Kant', 'Ludwig': 'Wittgenstein'}

#Ejemplo 13:

In [142]:
del estudiantes['hernan']
estudiantes

{'daniel': 'angelo', 'perdomo': 'morales'}

## Review: Python Dictionaries

- Unordered key-value mapping from (almost) arbitrary keys to arbitrary values.
- Efficient (`O(1)`) lookup, insertion, and deletion.
- No slicing (would require a notion of order).

<center><img src="images/pacino.gif" alt="Drawing" style="width: 100%;"/></center>


In [143]:
# Suppose we have some matrices...
a = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]

b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

#Ejemplo 14:

In [144]:

x = [[9, 8, 7],
     [83, 150, 12],
     [143, 416, 418],
     [201, 242, 244]]

y = [[32, 54, 74, 94],
     [151, 113, 145, 147]]

In [153]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

#Ejemplo 15:

In [152]:

def matmul(X, Y):
    """Multiply matrix A by matrix B."""
    rows_out = len(X)
    cols_out = len(Y[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(T)):
                out[i][j] += X[i][k] * Y[k][j]
    return out



<center><img src="images/gross.gif" alt="Drawing" style="width: 50%;"/></center>


In [154]:
%%time
matmul(a, b)

CPU times: user 38 µs, sys: 3 µs, total: 41 µs
Wall time: 45.3 µs


[[5, 8, 11, 14], [8, 13, 18, 23], [17, 28, 39, 50], [3, 5, 7, 9]]

#ejemplo 16:

In [155]:


%%time
matmul(x, y)

CPU times: user 42 µs, sys: 3 µs, total: 45 µs
Wall time: 50.1 µs


[[1496, 1390, 1826, 2022],
 [25306, 21432, 27892, 29852],
 [67392, 54730, 70902, 74594],
 [42974, 38200, 49964, 54468]]

In [156]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(2, 3)
randm

[[0.16557750779607772, 0.3469000493156299, 0.10145657320493828],
 [0.8892749883372055, 0.23376243416772058, 0.9705798255561975]]

#ejemplo 17:


In [157]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(4, 4)
randm

[[0.6478244777356085,
  0.11504588110503866,
  0.607331653596906,
  0.27586996918320306],
 [0.9023054727699805,
  0.38016149240647523,
  0.04984390698133623,
  0.4339874903781211],
 [0.17958015476835898,
  0.610678933972839,
  0.35266835929855,
  0.4906939750957263],
 [0.7662045843608971,
  0.31337970357301337,
  0.6784009401564732,
  0.44733936984459355]]

In [158]:
%%time
randa = random_matrix(600, 100)
randb = random_matrix(100, 600)
x = matmul(randa, randb)

CPU times: user 11 s, sys: 32.4 ms, total: 11 s
Wall time: 11.1 s


#ejemplo 18

In [159]:

%%time
randx = random_matrix(500, 200)
randy = random_matrix(150, 450)
z = matmul(randx, randy)

CPU times: user 10.9 s, sys: 41.4 ms, total: 11 s
Wall time: 11 s


In [160]:
# Maybe that's not that bad?  Let's try a simpler case.
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

#ejemplo 19

In [161]:
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))


In [162]:
list_data = [float(i) for i in range(100000)]
array_data = np.array(list_data)

#ejemplo 20:


In [163]:
list_datos = [float(i) for i in range(70000)]
array_datos = np.array(list_datos)

In [164]:
%%time
python_dot_product(list_data, list_data)

CPU times: user 15.1 ms, sys: 0 ns, total: 15.1 ms
Wall time: 18.9 ms


333328333350000.0

#ejemplo 21:

In [174]:
%%time
python_dot_product(list_datos, list_datos)


CPU times: user 10.2 ms, sys: 5 µs, total: 10.2 ms
Wall time: 11.2 ms


114330883345000.0

<center><img src="images/sloth.gif" alt="Drawing" style="width: 1080px;"/></center>


## Why is the Python Version so Much Slower?

In [180]:
# Dynamic typing.
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

[1, (4+0j), 9.0, 'fourfourfourfour']

#ejemplo 22:

In [179]:

def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([9, 8, 7, 6], [1, 2 + 3j, 7.0, 'nueve'])

[9, (16+24j), 49.0, 'nuevenuevenuevenuevenuevenueve']

## Why is the Python Version so Slow?
- Dynamic typing means that every single operation requires dispatching on the input type.
- Having an interpreter means that every instruction is fetched and dispatched at runtime.
- Other overheads:
  - Arbitrary-size integers.
  - Reference-counted garbage collection.

> This is the paradox that we have to work with when we're doing scientific or numerically-intensive Python. What makes Python fast for development -- this high-level, interpreted, and dynamically-typed aspect of the language -- is exactly what makes it slow for code execution.

- Jake VanderPlas, [*Losing Your Loops: Fast Numerical Computing with NumPy*](https://www.youtube.com/watch?v=EEUXKG97YRw)

# What Do We Do?

<center><img src="images/runaway.gif" alt="Drawing" style="width: 50%;"/></center>

<center><img src="images/thisisfine.gif" alt="Drawing" style="width: 1080px;"/></center>

- Python is slow for numerical computation because it performs dynamic dispatch on every operation we perform...

- ...but often, we just want to do the same thing over and over in a loop!

- If we don't need Python's dynamicism, we don't want to pay (much) for it.

- **Idea:** Dispatch **once per operation** instead of **once per element**.

In [182]:
import numpy as np

data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

#ejemplo 23:

In [183]:

dato = np.array([21, 24, 56, 48])
dato


array([21, 24, 56, 48])

#ejemplo 24:

In [185]:
data + data

array([2, 4, 6, 8])

In [184]:

dato + dato

array([ 42,  48, 112,  96])

In [187]:
%%time
# Naive dot product
(array_data * array_data).sum()

CPU times: user 0 ns, sys: 1.44 ms, total: 1.44 ms
Wall time: 868 µs


333328333350000.0

#ejemplo 25:

In [186]:
%%time
(array_dato * array_dato).sum()

CPU times: user 1.66 ms, sys: 0 ns, total: 1.66 ms
Wall time: 3.98 ms


114330883345000.0

In [188]:
%%time
# Built-in dot product.
array_data.dot(array_data)

CPU times: user 1.23 ms, sys: 3.07 ms, total: 4.29 ms
Wall time: 8.27 ms


333328333350000.0

#ejemplo 26:

In [189]:

array_dato.dot(array_dato)


114330883345000.0

In [192]:
%%time
fortran_dot_product(array_data, array_data)

#ejemplo 27:

In [193]:
%%time
fortran_dot_product(array_dato, array_dato)

In [194]:
# We **can** reshape an array though.
two_by_two = data.reshape(2, 2)
two_by_two

array([[1, 2],
       [3, 4]])

#ejemplo 28:

In [195]:

dos_por_dos = dato.reshape(2, 2)
dos_por_dos

array([[21, 24],
       [56, 48]])

Numpy arrays are:

- Fixed-type

- Size-immutable

- Multi-dimensional

- Fast\*

\* If you use them correctly.

# What's in an Array?

In [196]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype='int16').reshape(2, 3)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[1 2 3]
 [4 5 6]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00'


#ejemplo 29:

In [198]:


arr = np.array([9, 8, 7, 6, 5, 4], dtype='int16').reshape(3, 2)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[9 8]
 [7 6]
 [5 4]]
DType: int16
Shape: (3, 2)
Strides: (4, 2)
Data: b'\t\x00\x08\x00\x07\x00\x06\x00\x05\x00\x04\x00'


# Core Operations

- Vectorized **ufuncs** for elementwise operations.
- Fancy indexing and masking for selection and filtering.
- Aggregations across axes.
- Broadcasting

# UFuncs

UFuncs (universal functions) are functions that operate elementwise on one or more arrays.

In [199]:
data = np.arange(15).reshape(3, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#ejemplo 30:

In [202]:
dato = np.arange(20).reshape(4, 5)
dato

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [203]:
# Binary operators.
data * data

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

#ejemplo 31:

In [204]:

dato*dato

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361]])

In [205]:
# Unary functions.
np.sqrt(data)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

#ejemplo 32: 


In [206]:
np.sqrt(dato)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894]])

In [ ]:
# Comparison operations
(data % 3) == 0

#ejemplo 33:

In [207]:
(dato % 5) == 0

array([[ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False]])

In [210]:
# Boolean combinators.
((data % 2) == 0) & ((data % 3) == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]])

#ejemplo 34:

In [208]:
((dato % 2) == 0) & ((dato % 5) == 0)

array([[ True, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False]])

In [209]:
# as of python 3.5, @ is matrix-multiply
data @ data.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

#ejemplo 35:

In [211]:

dato @ dato.T


array([[  30,   80,  130,  180],
       [  80,  255,  430,  605],
       [ 130,  430,  730, 1030],
       [ 180,  605, 1030, 1455]])

# UFuncs Review

- UFuncs provide efficient elementwise operations applied across one or more arrays.
- Arithmetic Operators (`+`, `*`, `/`)
- Comparisons (`==`, `>`, `!=`)
- Boolean Operators (`&`, `|`, `^`)
- Trigonometric Functions (`sin`, `cos`)
- Transcendental Functions (`exp`, `log`)

# Selections

We often want to perform an operation on just a subset of our data.

In [212]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.14, 10))
sines

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

#ejemplo 36:

In [214]:

senos = np.sin(np.linspace(0, 1.2151, 19))
cosenos = np.cos(np.linspace(0, 2.2151, 19))
senos

array([0.        , 0.0674543 , 0.13460132, 0.2011352 , 0.26675285,
       0.33115538, 0.3940494 , 0.45514842, 0.51417411, 0.57085761,
       0.62494069, 0.676177  , 0.72433314, 0.76918975, 0.81054249,
       0.84820299, 0.8819997 , 0.91177866, 0.93740423])

In [215]:
# Slicing works with the same semantics as Python lists.
sines[0]

0.0

#ejemplo 37:

In [216]:
senos[0]

0.0

In [217]:
sines[:3]  # First three elements  

array([0.        , 0.34185385, 0.64251645])

#ejemplo 38:

In [ ]:

senos[:3]

In [218]:
sines[5:]  # Elements from 5 on.

array([0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

#ejemplo 39:

In [219]:
senos[5:]

array([0.33115538, 0.3940494 , 0.45514842, 0.51417411, 0.57085761,
       0.62494069, 0.676177  , 0.72433314, 0.76918975, 0.81054249,
       0.84820299, 0.8819997 , 0.91177866, 0.93740423])

In [221]:
sines[::2]  # Every other element.

array([0.        , 0.64251645, 0.98468459, 0.8665558 , 0.34335012])

#ejemplo 40:

In [220]:
senos[::2]

array([0.        , 0.13460132, 0.26675285, 0.3940494 , 0.51417411,
       0.62494069, 0.72433314, 0.81054249, 0.8819997 , 0.93740423])

In [222]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.5)
print("sines[sines > 0.5]:\n", sines[sines > 0.5])

sines:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]
sines > 0.5:
 [False False  True  True  True  True  True  True False False]
sines[sines > 0.5]:
 [0.64251645 0.86575984 0.98468459 0.98496101 0.8665558  0.64373604]


#ejemplo 41:

In [223]:

print("sines:\n", senos)
print("sines > 0.5:\n", senos > 0.5)
print("sines[sines > 0.5]:\n", senos[senos > 0.5])


sines:
 [0.         0.0674543  0.13460132 0.2011352  0.26675285 0.33115538
 0.3940494  0.45514842 0.51417411 0.57085761 0.62494069 0.676177
 0.72433314 0.76918975 0.81054249 0.84820299 0.8819997  0.91177866
 0.93740423]
sines > 0.5:
 [False False False False False False False False  True  True  True  True
  True  True  True  True  True  True  True]
sines[sines > 0.5]:
 [0.51417411 0.57085761 0.62494069 0.676177   0.72433314 0.76918975
 0.81054249 0.84820299 0.8819997  0.91177866 0.93740423]


In [224]:
# We index with lists/arrays of integers to select values at those indices.
print(sines)
sines[[0, 4, 7]]

[0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]


array([0.        , 0.98468459, 0.64373604])

#ejemplo 42:

In [226]:
 
print(senos)
senos[[0, 3, 7]]

[0.         0.0674543  0.13460132 0.2011352  0.26675285 0.33115538
 0.3940494  0.45514842 0.51417411 0.57085761 0.62494069 0.676177
 0.72433314 0.76918975 0.81054249 0.84820299 0.8819997  0.91177866
 0.93740423]


array([0.        , 0.2011352 , 0.45514842])

In [227]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data = np.array([1, 3, 2, 12, -1, 5, 2])

#ejemplo 43:

In [230]:
unsorted_dato = np.array([2332, 4235, 244656, 5645656, -546546, 678686, -7687887])

In [232]:
sort_indices = np.argsort(unsorted_data)
sort_indices

array([4, 0, 2, 6, 1, 5, 3])

#ejemplo 44:

In [231]:
sort_indice = np.argsort(unsorted_dato)
sort_indice

array([6, 4, 0, 1, 2, 5, 3])

In [233]:
unsorted_data[sort_indices]

array([-1,  1,  2,  2,  3,  5, 12])

#ejemplo 45:

In [234]:

unsorted_dato[sort_indice]

array([-7687887,  -546546,     2332,     4235,   244656,   678686,
        5645656])

In [235]:
market_caps = np.array([12, 6, 10, 5, 6])  # Presumably in dollars?
assets = np.array(['A', 'B', 'C', 'D', 'E'])

#ejemplo 46:

In [240]:
tienda_caps = np.array([123122, 643241, 21150, 5223,153216]) 
assets = np.array(['h', 'e', 'r', 'n', 'a'])

In [238]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap = np.argsort(market_caps)
assets[sort_by_mcap]

array(['n', 'e', 'a', 'r', 'h'], dtype='<U1')

#EJEMPLO 47:

In [241]:

sort_by_mcapo = np.argsort(tienda_caps)
assets[sort_by_mcapo]


array(['n', 'r', 'h', 'a', 'e'], dtype='<U1')

On multi-dimensional arrays, we can slice along each axis independently.

In [242]:
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#ejemplo 48:

In [244]:
dato = np.arange(49).reshape(7, 7)
dato

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [245]:
data[:2, :2]  # First two rows and first two columns.

array([[0, 1],
       [5, 6]])

#ejemplo 49:

In [246]:
dato[:2, :2]

array([[0, 1],
       [7, 8]])

In [247]:
data[:2, [0, -1]]  # First two rows, first and last columns.

array([[0, 4],
       [5, 9]])

#ejemplo 50:

In [248]:
dato[:2, [0, -1]]

array([[ 0,  6],
       [ 7, 13]])

In [250]:
data[(data[:, 0] % 2) == 0]  # Rows where the first column is divisible by two.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

#ejemplo 51:

In [249]:
dato[(dato[:, 0] % 2) == 0]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34],
       [42, 43, 44, 45, 46, 47, 48]])

# Selections Review

- Indexing with an integer removes a dimension.
- Slicing operations work on Numpy arrays the same way they do on lists.
- Indexing with a boolean array filters to True locations.
- Indexing with an integer array selects indices along an axis.
- Multidimensional arrays can apply selections independently along different axes.

## Reductions

Functions that reduce an array to a scalar.

$Var(X) = \frac{1}{N}\sqrt{\sum_{i=1}^N (x_i - \bar{x})^2}$

In [251]:
def variance(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

In [252]:
variance(np.random.standard_normal(1000))

1.0356804738878287

#ejemplo 52:

In [254]:
variance(np.random.standard_normal(2521))

1.0214010454972868

- `sum()` and `mean()` are both **reductions**.

- In the simplest case, we use these to reduce an entire array into a single value...

In [255]:
data = np.arange(30)
data.mean()

14.5

#ejemplo 53:

In [256]:
dato = np.arange(999)
dato.mean()

499.0

- ...but we can do more interesting things with multi-dimensional arrays.

In [257]:
data = np.arange(30).reshape(3, 10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

#ejemplo 54:

In [258]:
dato = np.arange(100).reshape(10, 10)
dato

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [259]:
data.mean()

14.5

#ejemplo 55:


In [260]:
dato.mean()


49.5

In [262]:
data.mean(axis=0)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

#ejemplo 56:

In [261]:

dato.mean(axis=0)

array([45., 46., 47., 48., 49., 50., 51., 52., 53., 54.])

In [263]:
data.mean(axis=1)

array([ 4.5, 14.5, 24.5])

#ejemplo 57:

In [ ]:
 
dato.mean(axis=1)

## Reductions Review

- Reductions allow us to perform efficient aggregations over arrays.
- We can do aggregations over a single axis to collapse a single dimension.
- Many built-in reductions (`mean`, `sum`, `min`, `max`, `median`, ...).

# Broadcasting

In [264]:
row = np.array([1, 2, 3, 4])
column = np.array([[1], [2], [3]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[1 2 3 4]
Column:
[[1]
 [2]
 [3]]


#ejemplo 58:

In [266]:
fila = np.array([9, 99, 9999, 99999])
columna = np.array([[19], [91991], [919191911]])
print("fila:\n", fila, sep='')
print("columna:\n", columna, sep='')

fila:
[    9    99  9999 99999]
columna:
[[       19]
 [    91991]
 [919191911]]


In [ ]:
row + column

#ejemplo 59:

In [268]:
fila + columna

array([[       28,       118,     10018,    100018],
       [    92000,     92090,    101990,    191990],
       [919191920, 919192010, 919201910, 919291910]])

<center><img src="images/broadcasting.png" alt="Drawing" style="width: 60%;"/></center>

<h5>Source: http://www.scipy-lectures.org/_images/numpy_broadcasting.png</h5>

In [269]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data, sep='')
print("Mean:\n", data.mean(axis=0), sep='')
print("Data - Mean:\n", data - data.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
Mean:
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
Data - Mean:
[[-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]


#ejemplo 60:


In [270]:
print("Data:\n", dato, sep='')
print("Mean:\n", dato.mean(axis=0), sep='')
print("Data - Mean:\n", dato - dato.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
Mean:
[45. 46. 47. 48. 49. 50. 51. 52. 53. 54.]
Data - Mean:
[[-45. -45. -45. -45. -45. -45. -45. -45. -45. -45.]
 [-35. -35. -35. -35. -35. -35. -35. -35. -35. -35.]
 [-25. -25. -25. -25. -25. -25. -25. -25. -25. -25.]
 [-15. -15. -15. -15. -15. -15. -15. -15. -15. -15.]
 [ -5.  -5.  -5.  -5.  -5.  -5.  -5.  -5.  -5.  -5.]
 [  5.   5.   5.   5.   5.   5.   5.   5.   5.   5.]
 [ 15.  15.  15.  15.  15.  15.  15.  15.  15.  15.]
 [ 25.  25.  25.  25.  25.  25.  25.  25.  25.  25.]
 [ 35.  35.  35.  35.  35.  35.  35.  35.  35.  35.]
 [ 45.  45.  45.  45.  45.  45.  45.  45.  45.  45.]]


# Broadcasting Review

- Numpy operations can work on arrays of different dimensions as long as the arrays' shapes are still "compatible".
- Broadcasting works by "tiling" the smaller array along the missing dimension.
- The result of a broadcasted operation is always at least as large in each dimension as the largest array in that dimension.

# Numpy Review

- Numerical algorithms are slow in pure Python because the overhead dynamic dispatch dominates our runtime.

- Numpy solves this problem by:
  1. Imposing additional restrictions on the contents of arrays.
  2. Moving the inner loops of our algorithms into compiled C code.

- Using Numpy effectively often requires reworking an algorithms to use vectorized operations instead of for-loops, but the resulting operations are usually simpler, clearer, and faster than the pure Python equivalent.

<center><img src="images/unicorn.jpg" alt="Drawing" style="width: 75%;"/></center>

Numpy is great for many things, but...

- Sometimes our data is equipped with a natural set of **labels**:
  - Dates/Times
  - Stock Tickers
  - Field Names (e.g. Open/High/Low/Close)

- Sometimes we have **more than one type of data** that we want to keep grouped together.
  - Tables with a mix of real-valued and categorical data.

- Sometimes we have **missing** data, which we need to ignore, fill, or otherwise work around.

<center><img src="images/panda-wrangling.gif" alt="Drawing" style="width: 75%;"/></center>

<center><img src="images/pandas_logo.png" alt="Drawing" style="width: 75%;"/></center>


Pandas extends Numpy with more complex data structures:

- `Series`: 1-dimensional, homogenously-typed, labelled array.
- `DataFrame`: 2-dimensional, semi-homogenous, labelled table.

Pandas also provides many utilities for: 
- Input/Output
- Data Cleaning
- Rolling Algorithms
- Plotting

# Selection in Pandas

In [271]:
s = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[1, 2, 3, 4, 5])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

#ejemplo 61:

In [272]:
x = pd.Series(index=['h', 'e', 'r', 'n', 'a'], data=[9, 8, 7, 6, 5])
x

h    9
e    8
r    7
n    6
a    5
dtype: int64

In [273]:
# There are two pieces to a Series: the index and the values.
print("The index is:", s.index)
print("The values are:", s.values)

The index is: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
The values are: [1 2 3 4 5]


#ejemplo 62:

In [274]:
print("The index is:", x.index)
print("The values are:", x.values)

The index is: Index(['h', 'e', 'r', 'n', 'a'], dtype='object')
The values are: [9 8 7 6 5]


In [275]:
# We can look up values out of a Series by position...
s.iloc[0]

1

#ejemplo 63:

In [276]:
x.iloc[0]

9

In [277]:
# ... or by label.
s.loc['a']

1

#ejemplo 64:

In [278]:
x.loc['r']

7

In [279]:
# Slicing works as expected...
s.iloc[:2]

a    1
b    2
dtype: int64

#ejemplo 65:

In [280]:
x.iloc[:2]

h    9
e    8
dtype: int64

In [282]:
# ...but it works with labels too!
s.loc[:'c']

a    1
b    2
c    3
dtype: int64

#ejemplo 66:

In [ ]:
x.loc[:'v']

In [281]:
# Fancy indexing works the same as in numpy.
s.iloc[[0, -1]]

a    1
e    5
dtype: int64

#ejemplo 67:

In [283]:

x.iloc[[0, -1]]

h    9
a    5
dtype: int64

In [284]:
# As does boolean masking.
s.loc[s > 2]

c    3
d    4
e    5
dtype: int64

#ejemplo 68:

In [285]:
x.loc[x > 144]

Series([], dtype: int64)

In [287]:
# Element-wise operations are aligned by index.
other_s = pd.Series({'a': 10.0, 'c': 20.0, 'd': 30.0, 'z': 40.0})
other_s

a    10.0
c    20.0
d    30.0
z    40.0
dtype: float64

#ejemplo 69:

In [290]:
other_x = pd.Series({'f': 13224, 'e': 22354, 'l': 5435, 'p': 44353.5})
other_x

f    13224.0
e    22354.0
l     5435.0
p    44353.5
dtype: float64

In [291]:
s + other_s

a    11.0
b     NaN
c    23.0
d    34.0
e     NaN
z     NaN
dtype: float64

#ejemplo 70:

In [292]:

x + other_x

a        NaN
e    22362.0
f        NaN
h        NaN
l        NaN
n        NaN
p        NaN
r        NaN
dtype: float64

In [293]:
# We can fill in missing values with fillna().
(s + other_s).fillna(0.0)

a    11.0
b     0.0
c    23.0
d    34.0
e     0.0
z     0.0
dtype: float64

#ejemplo 71:

In [294]:
(x + other_x).fillna(0.0)

a        0.0
e    22362.0
f        0.0
h        0.0
l        0.0
n        0.0
p        0.0
r        0.0
dtype: float64

# Pandas Review

- Pandas extends numpy with more complex datastructures and algorithms.
- If you understand numpy, you understand 90% of pandas.
- `groupby`, `set_index`, and `unstack` are powerful tools for working with categorical data.
- Avocado prices are surprisingly interesting :)

# Thanks!